### PR TITLE
Updates to Intro and Variables Lessons

### PR DESCRIPTION
**Pull request by pshriwise**
This is an update for a 50 minute lecture session. It starts from a slightly different perspective than most software carpentry type lessons, assuming that the students have ZERO experience programming or familiarity with MATLAB at all. 

The lessons I made move a little more slowly, but the next PR will contain lessons which gets more into arrays and scripts, demonstrating the power of MATLAB.

@cvoter if you wouldn't mind giving this a once-over I'd really appreciate it!! Not a frequent MATLAB user.

### CODE REVIEW

**Comment by cvoter** [comment]
Happy to! Planning to take a look later today or tomorrow morning at the latest.

**Comment by cvoter** [comment]
These look good! I like your approach of starting with variables, rather than the original version of "scripts". There are a few things I can think of that might be worth adding in these sections, or just keeping in mind as you teach:
* Since you can move elements of the MATLAB interface around, it's unlikely but possible some people's interface will be set up different. I personally like to add the "Command History" window (possible opportunity to emphasise "let the computer do the work").
* I see you took out discussion of the "Search Documentation" feature. I really like it since it's the best resource I know of for figuring out appropriate MATLAB commands. Possible illustrative example: searching "average" --> quickly realize "mean" is the appropriate command (unlike in Excel).
* Unlike some languages, spaces (e.g., around equal signs, arithmetic operators) don't matter in MATLAB.  This was confusing to me when I moved from MATLAB to other languages, and could(?) be confusing to these learners coming from Excel, where people typically don't use spaces.

**Comment by pshriwise** [comment]
This is all great stuff I probably would've left out. I'm making note of each of these. 

I think I'll bring up the search documentation bar at the end of class and use that example of `average` to find the `mean` function in the vein of the "teaching them to fish" philosophy we've been talking about in SWC on campus. 

Thanks again for taking the time to look this over!

**Comment by pshriwise** [comment]
- [x]  add information on the command history window
- [x] re-add the search documentation bar (add callout somewhere with example and mention at the end of the lecture)
- [x] mention that white space around operators doesn't matter in MATLAB

**Comment by pshriwise** [comment]
Thanks again for the comments @cvoter!

**Pull request merged**
